### ISSUE TITLE
Wallpaper show delay

### ISSUE THREAD

**Issue by ansarimohammed422** [Hamza417/Peri#102]
**Describe the bug**
So listen i have setup 2 folders from which peristyle fetches wallpapers
Now every time i open the app of go to foldersection
Both folders are not their
I have to add them back then they appear back

And when i go to homepage and comeback to folders section i have to repeat that process

**To Reproduce**

**Expected behavior**
I want those folders to appear first when i open folders section

**Screenshots**
![Screenshot_2024-10-24-21-03-16-291_app simple peri](https://github.com/user-attachments/assets/16c62858-4c66-45b1-8bd0-e1d87ada8d62)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. poco x6 pro]
 - OS: [e.g. Android 13]
 - Browser [e.g. stock browser]

**Additional context**

**Comment by Hamza417** [comment]
Has this started happening only after the recent update or was a common occurrence before?

**Comment by Hamza417** [comment]
Then clear the app data and start again, there is probably problem in folder permission retention in your device that is causing this issue.

**Comment by Hamza417** [comment]
Which device you are using and Android version?

**Comment by ansarimohammed422** [comment]
Poco x6 pro
Hyper os 1.0.5.0
Android 13

**Comment by Hamza417** [comment]
> Poco x6 pro
> Hyper os 1.0.5.0
> Android 13

I'm testing the app on a similar device and everything is working fine. The records of folders you allow the app to use is actually kept by the system and Peristyle only requests them when the folder screen is opened. If no folder is returned there is a possibility that something is not working correctly in your device.

**Comment by ansarimohammed422** [comment]
I am still facing this issue

The issue is whenever i open the app and go to folders section

I dont see any folders i have tried to wait also but the folders dont appear

But when i add them again they load and appear properly

Then i go back to home page and come to folder section again they disappear

One more thing

My wallpaper library is huge like i have 4500+ wallpapers

So is that an issue

**Comment by Hamza417** [comment]
> My wallpaper library is huge like i have 4500+ wallpapers

So is that an issue

No, it isn't. Folder screen only loads folders and takes less than a second to load. It doesn't load your wallpapers.

The only issue I can think of is you're using some app or mods that is wiping the persistable permissions of the app or something like that, and your folder permissions are removed as soon as you exit the app. You can try running the app in other device and see if it works in them.

**Comment by ansarimohammed422** [comment]
I caught the issue

I tried to be in folders section for seme time
And after waiting sometimes the folders appeared without adding them again

But then again when i go to home section and back to folders section the folders were not their so i have to wait some more time and after some delay the folders appeared

Whats causing them to disappear in the first place

**Comment by Hamza417** [comment]
> Whats causing them to disappear in the first place

I will have to check that

**Comment by Hamza417** [comment]
I ran a few tests and found that the list takes a long time to load if the folder doesn't have `.nomedia` file. The app has to traverse the whole list to look for it which in your case 4500 items which will take for about 12–15 seconds depending on how slow the scoped storage is.

**Comment by Hamza417** [comment]
I have optimized the loading time to less than 4-6 ms for loading folders containing 800+ wallpapers, which should mean the loading of folders data will be instantaneous now :)

**Comment by Hamza417** [comment]
It's fixed now...
